// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lwesample.proto

#include "lwesample.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace lwePb {
PROTOBUF_CONSTEXPR LweSample::LweSample(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.a_)*/{}
  , /*decltype(_impl_._a_cached_byte_size_)*/{0}
  , /*decltype(_impl_.current_variance_)*/0
  , /*decltype(_impl_.b_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct LweSampleDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LweSampleDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~LweSampleDefaultTypeInternal() {}
  union {
    LweSample _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LweSampleDefaultTypeInternal _LweSample_default_instance_;
}  // namespace lwePb
static ::_pb::Metadata file_level_metadata_lwesample_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_lwesample_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_lwesample_2eproto = nullptr;

const uint32_t TableStruct_lwesample_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::lwePb::LweSample, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::lwePb::LweSample, _impl_.a_),
  PROTOBUF_FIELD_OFFSET(::lwePb::LweSample, _impl_.b_),
  PROTOBUF_FIELD_OFFSET(::lwePb::LweSample, _impl_.current_variance_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::lwePb::LweSample)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::lwePb::_LweSample_default_instance_._instance,
};

const char descriptor_table_protodef_lwesample_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\017lwesample.proto\022\005lwePb\";\n\tLweSample\022\t\n"
  "\001a\030\001 \003(\005\022\t\n\001b\030\002 \001(\005\022\030\n\020current_variance\030"
  "\003 \001(\001By\n\016com.lwe.protosB\013LweSamplePBP\001Z3"
  "github.com/protocolbuffers/protobuf/prot"
  "os/go/lwepb\252\002\"Google.Protobuf.Protos.Lwe"
  "SamplePbb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_lwesample_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_lwesample_2eproto = {
    false, false, 216, descriptor_table_protodef_lwesample_2eproto,
    "lwesample.proto",
    &descriptor_table_lwesample_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_lwesample_2eproto::offsets,
    file_level_metadata_lwesample_2eproto, file_level_enum_descriptors_lwesample_2eproto,
    file_level_service_descriptors_lwesample_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_lwesample_2eproto_getter() {
  return &descriptor_table_lwesample_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_lwesample_2eproto(&descriptor_table_lwesample_2eproto);
namespace lwePb {

// ===================================================================

class LweSample::_Internal {
 public:
};

LweSample::LweSample(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:lwePb.LweSample)
}
LweSample::LweSample(const LweSample& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  LweSample* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.a_){from._impl_.a_}
    , /*decltype(_impl_._a_cached_byte_size_)*/{0}
    , decltype(_impl_.current_variance_){}
    , decltype(_impl_.b_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.current_variance_, &from._impl_.current_variance_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.b_) -
    reinterpret_cast<char*>(&_impl_.current_variance_)) + sizeof(_impl_.b_));
  // @@protoc_insertion_point(copy_constructor:lwePb.LweSample)
}

inline void LweSample::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.a_){arena}
    , /*decltype(_impl_._a_cached_byte_size_)*/{0}
    , decltype(_impl_.current_variance_){0}
    , decltype(_impl_.b_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

LweSample::~LweSample() {
  // @@protoc_insertion_point(destructor:lwePb.LweSample)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void LweSample::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.a_.~RepeatedField();
}

void LweSample::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void LweSample::Clear() {
// @@protoc_insertion_point(message_clear_start:lwePb.LweSample)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.a_.Clear();
  ::memset(&_impl_.current_variance_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.b_) -
      reinterpret_cast<char*>(&_impl_.current_variance_)) + sizeof(_impl_.b_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* LweSample::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated int32 a = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_a(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 8) {
          _internal_add_a(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 b = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.b_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // double current_variance = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 25)) {
          _impl_.current_variance_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* LweSample::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:lwePb.LweSample)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated int32 a = 1;
  {
    int byte_size = _impl_._a_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          1, _internal_a(), byte_size, target);
    }
  }

  // int32 b = 2;
  if (this->_internal_b() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_b(), target);
  }

  // double current_variance = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_current_variance = this->_internal_current_variance();
  uint64_t raw_current_variance;
  memcpy(&raw_current_variance, &tmp_current_variance, sizeof(tmp_current_variance));
  if (raw_current_variance != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(3, this->_internal_current_variance(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:lwePb.LweSample)
  return target;
}

size_t LweSample::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:lwePb.LweSample)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int32 a = 1;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      Int32Size(this->_impl_.a_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._a_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // double current_variance = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_current_variance = this->_internal_current_variance();
  uint64_t raw_current_variance;
  memcpy(&raw_current_variance, &tmp_current_variance, sizeof(tmp_current_variance));
  if (raw_current_variance != 0) {
    total_size += 1 + 8;
  }

  // int32 b = 2;
  if (this->_internal_b() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_b());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData LweSample::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    LweSample::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*LweSample::GetClassData() const { return &_class_data_; }


void LweSample::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<LweSample*>(&to_msg);
  auto& from = static_cast<const LweSample&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:lwePb.LweSample)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.a_.MergeFrom(from._impl_.a_);
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_current_variance = from._internal_current_variance();
  uint64_t raw_current_variance;
  memcpy(&raw_current_variance, &tmp_current_variance, sizeof(tmp_current_variance));
  if (raw_current_variance != 0) {
    _this->_internal_set_current_variance(from._internal_current_variance());
  }
  if (from._internal_b() != 0) {
    _this->_internal_set_b(from._internal_b());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void LweSample::CopyFrom(const LweSample& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:lwePb.LweSample)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LweSample::IsInitialized() const {
  return true;
}

void LweSample::InternalSwap(LweSample* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.a_.InternalSwap(&other->_impl_.a_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(LweSample, _impl_.b_)
      + sizeof(LweSample::_impl_.b_)
      - PROTOBUF_FIELD_OFFSET(LweSample, _impl_.current_variance_)>(
          reinterpret_cast<char*>(&_impl_.current_variance_),
          reinterpret_cast<char*>(&other->_impl_.current_variance_));
}

::PROTOBUF_NAMESPACE_ID::Metadata LweSample::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_lwesample_2eproto_getter, &descriptor_table_lwesample_2eproto_once,
      file_level_metadata_lwesample_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace lwePb
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::lwePb::LweSample*
Arena::CreateMaybeMessage< ::lwePb::LweSample >(Arena* arena) {
  return Arena::CreateMessageInternal< ::lwePb::LweSample >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
